pend_client/home/urls.py
from django.urls import path
from home import views

app_name = "home"


urlpatterns = [
    path('pendientes/list/',views.ListPendientesView.as_view(),name="list_pend"),
    path('pendientes/create/',views.CreatePendienteView.as_view(),name="create_pend"),
    # path('v1/create/grantgoal/',views.CreateGrantGoalAPIView.as_view(),name="create_gg_api"),
    # path('v1/Detail/grantgoal/',views.DetailGrantGoalAPIView.as_view(),name="detail_gg_api"),
    # path('v1/update/grantgoal/',views.UpdateGrantGoalAPIView.as_view(),name="update_gg_api"),
    # path('v1/delete/grantgoal/',views.DeleteGrantGoalAPIView.as_view(),name="delete_gg_api"),
]

pend_client/pend_client/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")),
]

pend_client/home/models.py
from django.db import models

# Create your models here.

pend_client/home/forms.py
from django import forms

CHOICES_PRIORITY = (
    ("ALTA", "ALT"),
    ("MEDIA", "MD"),
    ("BAJA", "BJ"),
)

CHIOCES_STATE = (
    ("SIN_RESOLVER", "Sin resolver"),
    ("PENDIENTE", "Pendiente"),
    ("RESUELTO", "Resuelto"),
)

class CreatePendienteForm(forms.Form):
        title = forms.CharField(max_length=32, widget= forms.TextInput(attrs={"type":"text", "class":"form-control"}))
        description= forms.CharField(max_length=32, widget= forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3}))
        priority= forms.CharField(max_length=16,widget=(forms.Select(choices=CHOICES_PRIORITY,attrs={'type':'select','class':'form-select'})))
        state = forms.CharField(max_length=16,widget=(forms.Select(choices=CHIOCES_STATE,attrs={'type':'select','class':'form-select'})))
        status = forms.BooleanField(initial=True)

pend_client/home/views.py
from django.shortcuts import render, redirect
from django.views import generic
import requests
from .forms import CreatePendienteForm

class ListPendientesView(generic.View):
    template_name = "home/list_pend.html"
    url = "http://127.0.0.1:8000/api/pendientes/list/"
    
    def get(self, request):
        response = requests.get(url=self.url)
        pendientes = response.json()

        filtro = request.GET.get('filtro', 'todos')

        if filtro == 'todos':
            context = {"pendientes": pendientes, "filtro": filtro}
        elif filtro == 'pendientes_ids':
            context = {"pendientes": [pd for pd in pendientes if pd['state'] == 'PENDIENTE'], "filtro": filtro}
        elif filtro == 'pendientes_ids_titles':
            context = {"pendientes": [pd for pd in pendientes if pd['state'] == 'PENDIENTE'], "filtro": filtro}
        elif filtro == 'pendientes_ids_userid':
            context = {"pendientes": [pd for pd in pendientes if pd['state'] == 'PENDIENTE'], "filtro": filtro}
        elif filtro == 'sin_resolver_ids_titles':
            context = {"pendientes": [pd for pd in pendientes if pd['state'] == 'SIN_RESOLVER'], "filtro": filtro}
        elif filtro == 'sin_resolver_ids_userid':
            context = {"pendientes": [pd for pd in pendientes if pd['state'] == 'SIN_RESOLVER'], "filtro": filtro}
        elif filtro == 'resueltos_ids_titles':
            context = {"pendientes": [pd for pd in pendientes if pd['state'] == 'RESUELTO'], "filtro": filtro}
        elif filtro == 'resueltos_ids_userid':
            context = {"pendientes": [pd for pd in pendientes if pd['state'] == 'RESUELTO'], "filtro": filtro}

        
        return render(request, self.template_name, context)

class CreatePendienteView(generic.View):
    template_name = "home/create_pend.html"
    context = {}
    payload = {}
    url = "http://127.0.0.1:8000/api/pendientes/create/"
    response = None
    form_class = CreatePendienteForm
    def get(self, request):
        self.context = {
            "form": self.form_class,
        }
        return render(request, self.template_name, self.context)

    def post(self, request):
        payload = {
            "title": request.POST["title"],
            "description": request.POST["description"],
            "user": request.user.username,
            "priority": request.POST["priority"],
            "state": request.POST["state"],
            "status": request.POST["status"],
            "user": 1
        }
        self.response = requests.post(url=self.url, data=payload)
        return redirect("home:list_pend")

pend_client/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Header Bootstrap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <div class="row">
    </div>
    <hr>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          {% block content %}
          {% endblock content %}
        </div>
        <div class="col-2"></div>
    </div>
    <hr>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

pend_client/templates/home/create_pend.html
{% extends "base/base.html" %}

{% block title %}Create pendiente{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">Crear Pendiente</button>
    </form>
{% endblock content %}

pend_client/templates/home/list_pend.html
{% extends "base/base.html" %}

{% block title %}TODOS LOS PENDIENTES{% endblock title %}

{% block content %}
    <table class="table table-striped">
        <div class="col-md-4">
            <a href="{% url 'home:create_pend' %}" class="btn btn-primary">Crear pendiente</a>
        </div>
        <thead>
            <th>ID</th>
            {% if filtro == "todos" or filtro == "pendientes_ids_titles" or filtro == "sin_resolver_ids_titles" or filtro == "resueltos_ids_titles" %}
                <th>Title</th>
            {% endif %}
            {% if filtro == "todos" or filtro == "pendientes_ids_userid" or filtro == "resueltos_ids_userid" or filtro == "sin_resolver_ids_userid" %}
                <th>User</th>
            {% endif %}
            {% if filtro == "todos" %}
                <th>Description</th>
                <th>Timestamp</th>
                <th>Priority</th>
                <th>State</th>
            {% endif %}
        </thead>
        <tbody>
            {% for pd in pendientes %}
                <tr>
                    <td>{{ pd.id }}</td>
                    {% if filtro == "todos" or filtro == "pendientes_ids_titles" or filtro == "sin_resolver_ids_titles" or filtro == "resueltos_ids_titles" %}
                        <td>{{ pd.title }}</td>
                    {% endif %}
                    {% if filtro == "todos" or filtro == "pendientes_ids_userid" or filtro == "resueltos_ids_userid" or filtro == "sin_resolver_ids_userid" %}
                        <td>{{ pd.user }}</td>
                    {% endif %}
                    {% if filtro == "todos" %}
                        <td>{{ pd.description }}</td>
                        <td>{{ pd.timestamp }}</td>
                        <td>{{ pd.priority }}</td>
                        <td>{{ pd.state }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <div class="col-md-4">
        <a href="?filtro=todos" class="btn btn-primary btn-block">Todos los pendientes</a>
    </div>
    <br>
    <div class="row">
        <div class="col-md-4">
            <a href="?filtro=pendientes_ids" class="btn btn-secondary btn-block">Pendientes (IDs)</a>
        </div>
        <div class="col-md-4">
            <a href="?filtro=pendientes_ids_titles" class="btn btn-secondary btn-block">Pendientes (IDs y Title)</a>
        </div>
        <div class="col-md-4">
            <a href="?filtro=pendientes_ids_userid" class="btn btn-secondary btn-block">Pendientes (IDs y UserID)</a>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-4">
            <a href="?filtro=sin_resolver_ids_titles" class="btn btn-warning btn-block">Sin resolver (IDs y Title)</a>
        </div>
        <div class="col-md-4">
            <a href="?filtro=sin_resolver_ids_userid" class="btn btn-warning btn-block">Sin resolver (IDs y UserID)</a>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-4">
            <a href="?filtro=resueltos_ids_titles" class="btn btn-success btn-block">Resueltos (IDs y Title)</a>
        </div>
        <div class="col-md-4">
            <a href="?filtro=resueltos_ids_userid" class="btn btn-success btn-block">Resueltos (IDs y UserID)</a>
        </div>
    </div>
{% endblock content %}